### ISSUE TITLE
Can not find model cam_utils

### ISSUE THREAD

**Issue by wangfei1204** [imatge-upc/retrieval-2017-cam#1]
when running A_Oxf_Par_Feat_CAMs_Extraction.py,  an error occurs: No module named cam_utils
where can I find this module. thanks for helping

**Comment by jsalbert** [comment]
Sorry I forgot to upload it. Now it should work.

**Comment by aiyanxiao** [comment]
/home/cvg/anaconda2/envs/keras2.7/bin/python2.7 /home/cvg/retrieval-2017-cam-master/keras_code/A_Dist_Feat_CAMs_Extraction.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/cvg/retrieval-2017-cam-master/keras_code/A_Dist_Feat_CAMs_Extraction.py", line 48, in <module>
    model = vggcam(nb_classes)
  File "/home/cvg/retrieval-2017-cam-master/keras_code/vgg_cam.py", line 27, in vggcam
    model.add(Convolution2D(64, 3, 3, activation='relu'))
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/keras/layers/convolutional.py", line 410, in build
    self.W = self.init(self.W_shape, name='{}_W'.format(self.name))
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/keras/initializations.py", line 57, in glorot_uniform
    fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/keras/initializations.py", line 15, in get_fans
    receptive_field_size = np.prod(shape[2:])
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2539, in prod
    out=out, **kwargs)
  File "/home/cvg/anaconda2/envs/keras2.7/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Please help me with this problem, Thanks!  In addition, what's the version of tensorflow used by you?
