### ISSUE TITLE
Problem of model = vggcam(nb_classes)

### ISSUE THREAD

**Issue by FzuLJ** [imatge-upc/retrieval-2017-cam#5]
`Traceback (most recent call last):
  File "A_Oxf_Par_Feat_CAMs_Extraction.py", line 71, in <module>
    model = vggcam(nb_classes)
  File "/home/linjie/src/CAM/keras_code/vgg_cam.py", line 27, in vggcam
    model.add(Convolution2D(64, 3, 3, activation='relu'))
  File "/home/linjie/anaconda2/lib/python2.7/site-packages/keras/models.py", line 522, in add
    output_tensor = layer(self.outputs[0])
  File "/home/linjie/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 592, in __call__
    self.build(input_shapes[0])
  File "/home/linjie/anaconda2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 129, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
`

Hi, I met this problem when I ran A_Oxf_Par_Feat_CAMs_Extraction.py . It seems like the parameters of the function vggcam is incomplete. Does anyone know how to solve this problem? 
Thank you.

**Comment by FancyXun** [comment]
add the following code in vgg_cam.py
os.environ['KERAS_BACKEND'] = 'theano'
K.set_image_data_format('channels_first')
